### ISSUE TITLE
这里写错了

### ISSUE THREAD

**Issue by zhalice2011** [mtianyan/movie_project#1]
#（设置外键的第二步）
    userlogs = db.relationship('userlog',backref = 'user')#会员日志外键关系关联
应该是大写  指向的是应该引用类，而不是实际表
    userlogs = db.relationship('Userlog',backref = 'user')#会员日志外键关系关联

**Comment by mtianyan** [comment]
谢谢提醒，前段时间考研去了，项目就没有继续写了。最近会继续写这个的代码+教程的。 @zhalice2011

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
