### ISSUE TITLE
简书链接打不开了

### ISSUE THREAD

**Issue by liujiachao** [mtianyan/movie_project#11]
想学习一下教程，但是简书链接打开显示404

**Comment by mtianyan** [comment]
@liujiachao  简书被以有可能抄袭为由封号了，正在申诉请求知道哪些涉及又是抄袭了谁的细节。一直没有回复，不知道什么时候才能解封或者永远都不会了_§:з)))」∠)_ 欢迎加群 619417153 ，群文件有简书博客原始markdown。
