### ISSUE TITLE
你这个代码是不是没有完整？

### ISSUE THREAD

**Issue by lDaisy847800926** [mtianyan/movie_project#2]
请问你这个代码是跟慕课网上面的Flask微视频这个一样的吗/

**Comment by VegetableCat** [comment]
是的 commit log里面对应的视频信息 可见po主没有看完视频

**Comment by VegetableCat** [comment]
https://github.com/yujialian/movie_project

**Comment by mtianyan** [comment]
是一样的。不过我前段时间考研去了，之后就没有写这个项目了。最近我会把这个的代码+教程写完的。 @lDaisy847800926  @VegetableCat

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
