### ISSUE TITLE
关于电影添加方法中文件没法上传

### ISSUE THREAD

**Issue by Rocky-Li-Adam** [mtianyan/movie_project#7]
app/admin/views.py --> movie_add() --> file_url = secure_filename(form.url.data.filename)
这段程序提示 AttributeError: 'str' object has no attribute 'filename'
form.url.data的类型是str，没有filename属性

**Comment by Rocky-Li-Adam** [comment]
应该改成
file_url = secure_filename(data['url'].filename) 和 data['url'].save()

**Comment by mtianyan** [comment]
@Rocky-Li-Adam 你的版本是否和我用的不一致。我代码在我那些版本的环境下当时是好的。

**Comment by Rocky-Li-Adam** [comment]
应该是我模板的form表单中没添加 enctype="multipart/form-data" 属性的原因。
